# Site settings
title: Golem Foundation
#description: > # this means to ignore newlines until "baseurl:"
#        TODO
#        TODO
#        TODO
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://golem.foundation" # the base hostname & protocol for your site
#twitter_username: TODO
github_username:  golemfoundation

# Build settings
markdown: kramdown
